name: CI (Build and Deploy)

on:
  push:
    branches: [ trunk ]
  workflow_dispatch:
    inputs:
      job_to_run:
        description: 'Select the job to run'
        required: true
        options:
          - deploy_repo
      branch:
        description: 'Branch to deploy to (only applicable if "deploy_repo" is selected)'
        required: false
        default: 'trunk'

jobs:
  prepare_repo:
    name: Prepare repo (always runs)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare the repo
        uses: ./.github/actions/prepare
        with:
          php_version: ${{ env.PHP_VERSION }}

  deploy_repo:
    name: Deploy repo (only runs if 'deploy_repo' is selected in workflow dispatch)
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'deploy_repo' && github.event.inputs.branch == 'trunk' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare the repo
        uses: ./.github/actions/prepare
        with:
          php_version: ${{ env.PHP_VERSION }}

      - name: Replace .gitignore with .deployignore
        shell: bash
        run: |
          if [ -f .deployignore ]; then
            mv .deployignore .gitignore
          else
            echo "No .deployignore file found, skipping replacement."
          fi

      - name: commit to built branch
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy assets for ${{ inputs.php_version }}"
          git push origin HEAD:${{ inputs.branch }}-built --force
