name: Build and test repository (runs on every push)

on:
  pull_request:
  push:
    branches-ignore:
      - "**-built"
      - "**-built-**"

jobs:
  build_and_test:
    name: Build and test repo (runs on every push )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare the repo
        uses: ./.github/actions/prepare
        with:
          php_version: ${{ env.PHP_VERSION }}

      - name: Replace .gitignore with .deployignore (only trunk branch)
        if: ${{ github.ref == 'refs/heads/trunk' }}
        shell: bash
        run: |
          if [ -f .deployignore ]; then
            mv .deployignore .gitignore
          else
            echo "No .deployignore file found, skipping replacement."
          fi

      - name: commit built trunk branch
        if: ${{ github.ref == 'refs/heads/trunk' }}
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy assets for ${{ inputs.php_version }}"
          git push origin HEAD:trunk-built --force
